# Generated by Django 5.0.7 on 2024-08-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='users/images'),
        ),
    ]
