# Generated by Django 5.0.7 on 2024-07-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField()),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.city')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.state')),
            ],
        ),
    ]
