# Generated by Django 5.0.7 on 2024-08-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_city_id_alter_seller_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
