# Generated by Django 5.0.7 on 2024-10-12 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_total_prod_qtys_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
