# Generated by Django 5.0.7 on 2024-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=14, null=True),
        ),
    ]
