# Generated by Django 5.0.7 on 2024-09-01 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimages_product_id_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='fallback.png', upload_to='product_images/'),
        ),
    ]
