# Generated by Django 5.0.7 on 2024-09-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='product_images/product_fallback.png', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
